import type { Metadata } from 'next';
import './globals.css';
import Header from './components/header/Header';
import { Provider } from 'jotai';
import ThemeProvider from './contexts/ThemeContext';
import ThemeWrapper from './contexts/ThemeWrapper';
import Footer from './components/mainPage/Footer';
import ProgressBar from './components/ProgressBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/app/favicon/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <ThemeProvider>
            <ThemeWrapper>
              <Header />
              <main>{children}</main>
              <Footer />
            </ThemeWrapper>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
